jobs:
  enable-workflow:
    needs:
      - linux
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{github.token}}
        run: gh workflow enable workflow.yml --repo "$GITHUB_REPOSITORY"
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: docker build --pull -f container/Dockerfile .
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '13 3 * * WED'
